import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

export interface DemoTracePayload {
  meta: {
    title: string;
    network: string;
    contractId: string;
    roundId: number;
    revealRound: number;
    clearingRule: "HighestBid" | "LowestBid";
    recordedAt: string;
    roundStatus: string;
    liveE2e: string[];
    proofScope: string;
  };
  lifecycle: Array<{
    phase: string;
    label: string;
    detail: string;
    status: "done" | "active" | "pending";
  }>;
  bidders: Array<{
    label: string;
    address: string;
    role: "agent" | "human";
    escrowUsdc: number;
    bidUsdc: number | null;
    revealed: boolean;
    valid: boolean;
    winner: boolean;
  }>;
  agents: Array<{
    name: string;
    principal: string;
    sessionKey: string;
    mandate: {
      maxBidUsdc: number;
      maxEscrowUsdc: number;
      maxAppraisalSpendUsdc: number;
      cappedAtMaxBid: boolean;
    };
    appraisal: {
      fairValue: number;
      suggestedMaxBid: number;
      inputsHash: string;
    };
    x402: { priceUsdc: number; settled: boolean };
    commitTx?: string;
  }>;
  keeper: {
    drandRound: number;
    blsVerifiedOnChain: boolean;
    reveals: string[];
    clearWinner?: string;
    contractBalanceFinal: number;
  };
  settlement: {
    operatorReceivedUsdc: number;
    refundsUsdc: number;
    note: string;
  };
  auditor: {
    source: string;
    generatedAt: string;
    secretHex: string;
    publicHex: string;
    blobs: Record<string, string>;
  };
}

const repoPath = (path: string) =>
  path.startsWith("/") ? path : resolve(process.cwd(), "../..", path);

export async function writeDemoTrace(
  path: string,
  trace: DemoTracePayload,
): Promise<void> {
  const out = repoPath(path);
  await mkdir(dirname(out), { recursive: true });
  const body = [
    "// Generated by `pnpm agents:e2e` — canonical jury demo trace.",
    "// Do not edit by hand; re-run agents:e2e to refresh.",
    "",
    `export const DEMO_TRACE = ${JSON.stringify(trace, null, 2)} as const;`,
    "",
  ].join("\n");
  await writeFile(out, body);
  console.log("    ✔ web demo trace:", out);
}
