// Generated by `pnpm agents:e2e` — canonical jury demo trace.
// Do not edit by hand; re-run agents:e2e to refresh.

export const DEMO_TRACE = {
  "meta": {
    "title": "Spectrum Block Allocation — Round 1",
    "network": "Stellar Testnet",
    "contractId": "CAPTODBCDEVIK23ALBJBS2TXRTIK47ZA5MBTHYF4XLHG2BK7JPYUCU2Y",
    "roundId": 1,
    "revealRound": 29176840,
    "clearingRule": "HighestBid",
    "recordedAt": "2026-06-01T17:14:46.200Z",
    "roundStatus": "Settled",
    "liveE2e": [
      "pnpm agents:e2e",
      "pnpm mainnet:verify"
    ],
    "proofScope": "Single canonical testnet run: 2 mandated agents, x402 appraisal, sealed commits, permissionless keeper reveal, clear, settle → contract 0 USDC."
  },
  "lifecycle": [
    {
      "phase": "create_round",
      "label": "Create round",
      "detail": "Operator opens round with Drand reveal round R, commit/reveal deadlines, auditor key.",
      "status": "done"
    },
    {
      "phase": "commit",
      "label": "Agents commit",
      "detail": "Two session-mandated agents pay x402 appraisal, seal bids to R, lock USDC escrow.",
      "status": "done"
    },
    {
      "phase": "wait_r",
      "label": "Wait for Drand R",
      "detail": "Bids are undecryptable until quicknet publishes round R (~3s cadence).",
      "status": "done"
    },
    {
      "phase": "open_reveal",
      "label": "Open reveal",
      "detail": "Permissionless keeper submits R's BLS signature — verified on-chain via Soroban host.",
      "status": "done"
    },
    {
      "phase": "reveal_all",
      "label": "Reveal all",
      "detail": "Keeper decrypts every seal and reveals — selective abort is impossible.",
      "status": "done"
    },
    {
      "phase": "clear",
      "label": "Clear",
      "detail": "After reveal deadline: deterministic winner (highest valid bid).",
      "status": "done"
    },
    {
      "phase": "settle",
      "label": "Settle",
      "detail": "Winner pays operator; losers + surplus refunded. Contract balance → 0.",
      "status": "done"
    }
  ],
  "bidders": [
    {
      "label": "agent-alpha",
      "address": "GAKZTF6HNE2CKUDFQUO5F2XNGWXSG3QI3NO7DXFMRAVIQKEO6NIJT7NQ",
      "role": "agent",
      "escrowUsdc": 700,
      "bidUsdc": 700,
      "revealed": true,
      "valid": true,
      "winner": true
    },
    {
      "label": "agent-beta",
      "address": "GCO5ETWJKVYYVGUCTTRCXDWNQAZNIZ3F4LWZI5VRF6CBTKUSBSQ7CUQR",
      "role": "agent",
      "escrowUsdc": 459.34,
      "bidUsdc": 459.34,
      "revealed": true,
      "valid": true,
      "winner": false
    }
  ],
  "agents": [
    {
      "name": "agent-alpha",
      "principal": "GCHQS4U3Y2BJG7F6FNQBQLDRT7BG5PUJHEIX546MHCR4QFCBFGSHPKJS",
      "sessionKey": "GAKZTF6HNE2CKUDFQUO5F2XNGWXSG3QI3NO7DXFMRAVIQKEO6NIJT7NQ",
      "mandate": {
        "maxBidUsdc": 700,
        "maxEscrowUsdc": 700,
        "maxAppraisalSpendUsdc": 1,
        "cappedAtMaxBid": true
      },
      "appraisal": {
        "fairValue": 1291.19,
        "suggestedMaxBid": 1226.63,
        "inputsHash": "090413b29bf8163eead7f46a425ccfd3ac78ea62ea361ec4d74f3c4d5429b488"
      },
      "x402": {
        "priceUsdc": 0.1,
        "settled": true
      },
      "commitTx": "on-chain via session key"
    },
    {
      "name": "agent-beta",
      "principal": "GCYVQDSP4XUBFNW2CNPEX76IXOBR5XGYA4Z2T4NR7SDICUWT7POSNIYJ",
      "sessionKey": "GCO5ETWJKVYYVGUCTTRCXDWNQAZNIZ3F4LWZI5VRF6CBTKUSBSQ7CUQR",
      "mandate": {
        "maxBidUsdc": 700,
        "maxEscrowUsdc": 700,
        "maxAppraisalSpendUsdc": 1,
        "cappedAtMaxBid": false
      },
      "appraisal": {
        "fairValue": 483.52,
        "suggestedMaxBid": 459.34,
        "inputsHash": "286a8d8058afb24c53f81a71d49bf1235274fa76af2e1fc1267bebc3c5640920"
      },
      "x402": {
        "priceUsdc": 0.1,
        "settled": true
      },
      "commitTx": "on-chain via session key"
    }
  ],
  "keeper": {
    "drandRound": 29176840,
    "blsVerifiedOnChain": true,
    "reveals": [
      "agent-alpha → 700 USDC",
      "agent-beta → 459.34 USDC"
    ],
    "clearWinner": "GAKZTF6HNE2CKUDFQUO5F2XNGWXSG3QI3NO7DXFMRAVIQKEO6NIJT7NQ",
    "contractBalanceFinal": 0
  },
  "settlement": {
    "operatorReceivedUsdc": 700,
    "refundsUsdc": 459.34,
    "note": "Winner pays bid from escrow; loser refunded in full. Contract holds 0 USDC after settle."
  },
  "auditor": {
    "source": "agents:e2e",
    "generatedAt": "2026-06-01T17:14:46.200Z",
    "secretHex": "0352d1841643949f36a5f4a42e37cfae0c78f7a71e8cba7f75635655910dd391",
    "publicHex": "00b1a86f86523448f85ba253fd5203abfbc38507aeae82ac163144faf6193a48",
    "blobs": {
      "agent-alpha": "bb5cac436cf12d5f4b899adbfb0d61856a45d6574bc5dd0d1ba9c80780a7002e13136552e655738aa602d2790f54cc7d5207f3d6e53948272427b1ce08b1e1ec812cc86f774c3f0a59f4e69ced04e30915d18fd81382d3a70ed9eddb24e9083e0d9bf1df8f884676979deb507e55b3f09977e373552c7011cebaee7335376e9c42a0cbe4eb1e",
      "agent-beta": "f9e9cd9246380f20000b9f4f753fe1d3ea03764d6f57c2615a3e7688b27bb843058b1dfa2fdae1aab3f0e059a618816ff4d740f59e0490ef303cb3ee3142f4a9b9b1288b1421b62e860063be90b4c3abf1a8bedd4ebb9e01518322a1afc1f1e4a1adf56248fad001b19f874b82d29358a03a5c08fa35d8290d6f3487105499638cef3c42cb8f"
    }
  }
} as const;
