export {
  keepRound,
  closeRound,
  voidIfStale,
  discoverRoundIds,
  parseRoundIdSpec,
  watchRound,
  waitForRound,
  errorName,
  errorMatches,
  VOID_GRACE_SECONDS,
  type KeeperDeps,
  type KeeperResult,
  type CloseResult,
  type VoidResult,
  type WatchTickResult,
  type KeeperLogger,
  type SkipRecord,
} from "./keeper.js";
